package eu_data_act

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/shift/enrichment-engine/pkg/storage"
)

const (
	FrameworkID = "EU_DATA_ACT_2023_2854"
	CatalogURL  = ""
)

type Control struct {
	Framework              string      `json:"Framework"`
	ControlID              string      `json:"ControlID"`
	Title                  string      `json:"Title"`
	Family                 string      `json:"Family,omitempty"`
	Description            string      `json:"Description,omitempty"`
	Level                  string      `json:"Level,omitempty"`
	RelatedCWEs            []string    `json:"RelatedCWEs,omitempty"`
	RelatedCVEs            []string    `json:"RelatedCVEs,omitempty"`
	References             []Reference `json:"References,omitempty"`
	ImplementationGuidance string      `json:"ImplementationGuidance,omitempty"`
	AssessmentMethods      []string    `json:"AssessmentMethods,omitempty"`
}

type Reference struct {
	Source  string `json:"source,omitempty"`
	URL     string `json:"url,omitempty"`
	Section string `json:"section,omitempty"`
}

type Provider struct {
	store  storage.Backend
	logger *slog.Logger
}

func New(store storage.Backend, logger *slog.Logger) *Provider {
	return &Provider{
		store:  store,
		logger: logger,
	}
}

func (p *Provider) Name() string {
	return "eu_data_act"
}

func (p *Provider) Run(ctx context.Context) (int, error) {
	return p.writeEmbeddedControls(ctx)
}

func (p *Provider) writeEmbeddedControls(ctx context.Context) (int, error) {
	p.logger.Info("using embedded EU Data Act controls")

	controls := embeddedControls()
	count := 0
	for _, ctrl := range controls {
		id := fmt.Sprintf("%s/%s", FrameworkID, ctrl.ControlID)
		if err := p.store.WriteControl(ctx, id, ctrl); err != nil {
			p.logger.Warn("failed to write control", "id", id, "error", err)
			continue
		}
		count++
	}

	p.logger.Info("wrote embedded EU Data Act controls to storage", "count", count)
	return count, nil
}

func embeddedControls() []Control {
	controls := []Control{}

	dataSharingBusiness := []struct {
		id, title, desc, article string
	}{
		{"DA-3.1", "Obligation to share data", "Data holders shall make data generated by the use of connected products or related services available to users and third parties upon request, without undue delay, where the data is necessary for the provision of a specific aftermarket service or for interoperability.", "Article 3"},
		{"DA-3.2", "Scope of data sharing obligation", "The obligation to share data shall cover data that is generated by the use of a connected product or related service and that is technically necessary and proportionate for the purpose requested by the data recipient.", "Article 3"},
		{"DA-4.1", "Access to data by users", "Users shall have the right to access the data generated by the use of connected products or related services which they own, rent, or lease, including data they have provided themselves and generated data.", "Article 4"},
		{"DA-4.2", "Data access without undue delay", "Users shall be provided with access to their data in a timely manner, without undue delay, and in a structured, commonly used, and machine-readable format.", "Article 4"},
		{"DA-5.1", "Compensation for data sharing", "Data holders may receive fair, reasonable, and non-discriminatory compensation for the costs incurred in making data available, including costs for infrastructure, data processing, and technical measures.", "Article 5"},
		{"DA-5.2", "Compensation framework conditions", "The compensation shall be proportionate to the economic value of the data shared and the actual costs of making it available, and shall not create barriers to data-driven innovation.", "Article 5"},
		{"DA-6.1", "Trade secrets protection", "Data holders shall not be obliged to share data that constitutes a trade secret within the meaning of Directive (EU) 2016/943 when sharing would undermine the protection of that trade secret.", "Article 6"},
		{"DA-6.2", "Safeguarding intellectual property rights", "The obligation to share data shall not affect the protection of intellectual property rights, including patents, design rights, copyrights, and database rights under Union law.", "Article 6"},
		{"DA-7.1", "Dispute resolution mechanisms", "Competent authorities shall establish dispute resolution mechanisms for disputes between data holders and data recipients regarding the terms and conditions of data sharing.", "Article 7"},
		{"DA-8.1", "Voluntary data sharing", "Data holders may voluntarily share data with third parties beyond the mandatory obligations, subject to agreements that specify the purpose, scope, and conditions of the data sharing.", "Article 8"},
	}

	dataSharingPublicSector := []struct {
		id, title, desc, article string
	}{
		{"DA-14.1", "Exceptional access for public sector bodies", "Public sector bodies may request access to data held by private enterprises that is necessary for the performance of a task carried out in the public interest, under exceptional circumstances.", "Article 14"},
		{"DA-14.2", "Public interest purposes", "Exceptional data access shall be limited to purposes related to public health, environmental protection, crisis management, and response to emergencies that cannot be fulfilled without such access.", "Article 14"},
		{"DA-15.1", "Conditions for data access", "Public sector bodies shall demonstrate that the data requested cannot be reasonably obtained by other means, that the request is proportionate, and that the data will be processed in accordance with data protection law.", "Article 15"},
		{"DA-15.2", "Data minimisation and purpose limitation", "Access to data by public sector bodies shall be limited to what is necessary and proportionate for the stated public interest purpose, and shall not be retained beyond the period necessary.", "Article 15"},
		{"DA-16.1", "Data protection safeguards", "All data sharing with public sector bodies shall comply with the General Data Protection Regulation (GDPR) and ensure appropriate technical and organisational measures are in place to protect personal data.", "Article 16"},
	}

	cloudSwitching := []struct {
		id, title, desc, article string
	}{
		{"DA-28.1", "Prohibition of switching barriers", "Cloud service providers shall not design, structure, or implement their services in a way that creates technical, contractual, or commercial barriers preventing or limiting cloud switching.", "Article 28"},
		{"DA-28.2", "Transparent switching terms", "Cloud service providers shall provide clear, comprehensive, and accessible information about the conditions, procedures, and costs associated with switching to another provider or returning to an on-premise solution.", "Article 28"},
		{"DA-29.1", "Prohibition of exit fees", "Cloud service providers shall not charge exit fees or impose penalties on customers who terminate their contract to switch to another provider or revert to an on-premise solution.", "Article 29"},
		{"DA-29.2", "Data portability and format requirements", "Cloud service providers shall ensure that customers can extract their data in a structured, commonly used, and machine-readable format at any time during and upon termination of the contract.", "Article 29"},
		{"DA-30.1", "Interoperability of cloud services", "Cloud service providers shall ensure that their services are interoperable with other cloud services and with on-premise solutions, enabling seamless data exchange and service continuity.", "Article 30"},
	}

	interoperability := []struct {
		id, title, desc, article string
	}{
		{"DA-31.1", "IoT data interoperability", "Manufacturers of connected products shall ensure that data generated by their products can be accessed, processed, and shared in a manner that supports interoperability with products and services from other manufacturers.", "Article 31"},
		{"DA-32.1", "Real-time data access standards", "Where data needs to be accessed and processed in real-time, data holders shall provide access through standardized interfaces and protocols that ensure low-latency and reliable data transmission.", "Article 32"},
		{"DA-33.1", "Technical standards compliance", "Connected products and related services shall comply with harmonised European standards or common specifications adopted pursuant to the relevant EU legislation on interoperability.", "Article 33"},
		{"DA-34.1", "API-based data access", "Data holders shall provide access to data through application programming interfaces (APIs) that are documented, secure, and available on fair, reasonable, and non-discriminatory terms.", "Article 34"},
		{"DA-35.1", "Data quality and metadata", "Data holders shall ensure that shared data is accompanied by relevant metadata describing its provenance, quality, format, and any applicable usage conditions.", "Article 35"},
	}

	edgeCloudGateways := []struct {
		id, title, desc, article string
	}{
		{"DA-36.1", "Access conditions for edge/cloud gateways", "Providers of edge and cloud gateway services shall establish transparent and non-discriminatory access conditions for third-party providers of data processing services.", "Article 36"},
		{"DA-37.1", "Notification of access conditions", "Gateway providers shall publish and notify the competent authority of the access conditions applied to third-party data processing service providers, including any changes to those conditions.", "Article 37"},
		{"DA-37.2", "Non-discrimination of gateway services", "Gateway providers shall not discriminate against specific categories of third-party service providers or give preferential treatment to their own data processing services over those of competitors.", "Article 37"},
		{"DA-38.1", "Compliance and enforcement", "Competent authorities shall monitor compliance with the gateway access conditions and may impose penalties for non-compliance, including requiring changes to access conditions or granting access on specific terms.", "Article 38"},
	}

	for _, c := range dataSharingBusiness {
		controls = append(controls, Control{
			Framework:   FrameworkID,
			ControlID:   c.id,
			Title:       c.title,
			Family:      "Data Sharing by Businesses",
			Description: c.desc,
			Level:       "standard",
			References: []Reference{
				{Source: "EU Data Act (Regulation 2023/2854)", Section: c.article},
			},
		})
	}

	for _, c := range dataSharingPublicSector {
		controls = append(controls, Control{
			Framework:   FrameworkID,
			ControlID:   c.id,
			Title:       c.title,
			Family:      "Data Sharing with Public Sector Bodies",
			Description: c.desc,
			Level:       "standard",
			References: []Reference{
				{Source: "EU Data Act (Regulation 2023/2854)", Section: c.article},
			},
		})
	}

	for _, c := range cloudSwitching {
		controls = append(controls, Control{
			Framework:   FrameworkID,
			ControlID:   c.id,
			Title:       c.title,
			Family:      "Cloud Switching",
			Description: c.desc,
			Level:       "standard",
			References: []Reference{
				{Source: "EU Data Act (Regulation 2023/2854)", Section: c.article},
			},
		})
	}

	for _, c := range interoperability {
		controls = append(controls, Control{
			Framework:   FrameworkID,
			ControlID:   c.id,
			Title:       c.title,
			Family:      "Interoperability",
			Description: c.desc,
			Level:       "standard",
			References: []Reference{
				{Source: "EU Data Act (Regulation 2023/2854)", Section: c.article},
			},
		})
	}

	for _, c := range edgeCloudGateways {
		controls = append(controls, Control{
			Framework:   FrameworkID,
			ControlID:   c.id,
			Title:       c.title,
			Family:      "Edge and Cloud Gateways",
			Description: c.desc,
			Level:       "standard",
			References: []Reference{
				{Source: "EU Data Act (Regulation 2023/2854)", Section: c.article},
			},
		})
	}

	return controls
}
